version: '3'
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB={POSTGRES_DB}
      - POSTGRES_USER={POSTGRES_USER}
      - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/redis/redis_data:/data
    expose:
      - "6379"
    ports:
      - "6379:6379"
    env_file:
      - .env
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass "${REDIS_PASSWORD}"

  web:
    image: hordiirushynets/dia-subscription:latest
    build: .
    command:
      bash -c "
      sleep 1
      && python manage.py makemigrations
      && python manage.py migrate
      && gunicorn --bind 0.0.0.0:8000 dia_subscription.wsgi:application"
    restart: always
    volumes:
      - .:/app
      - ./static:/var/static
      - ./media:/var/media
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      - redis
      - db
    env_file:
      - .env

volumes:
  postgres_data: