# Generated by Django 3.2.25 on 2024-10-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dia_subscription_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SubsciptedUser',
        ),
    ]
