# Generated by Django 3.2.25 on 2024-10-16 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dia_subscription_users', '0003_auto_20241015_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signer',
            name='vote',
        ),
        migrations.AddField(
            model_name='company',
            name='business_type',
            field=models.CharField(choices=[('small', 'small'), ('veterans', 'veterans')], default='small', max_length=15),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='signer',
            name='vote_business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_business', to='dia_subscription_users.company'),
        ),
        migrations.AddField(
            model_name='signer',
            name='vote_business_veterans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_business_veterans', to='dia_subscription_users.company'),
        ),
    ]
